// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYmWkX3JxWzKUX0uoImwWBndZDhK5cHW0',
    appId: '1:564462594743:web:d837f5284d62a2c343bb32',
    messagingSenderId: '564462594743',
    projectId: 'wigo-trip-planner',
    authDomain: 'wigo-trip-planner.firebaseapp.com',
    storageBucket: 'wigo-trip-planner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8whxnu-_1-ZDi_BQ3lkgMNFji7pg7L7s',
    appId: '1:564462594743:android:46dba420514719a643bb32',
    messagingSenderId: '564462594743',
    projectId: 'wigo-trip-planner',
    storageBucket: 'wigo-trip-planner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx5Q4bInlYx5SVSFKECqPYPHED2XWSV7A',
    appId: '1:564462594743:ios:1c2d31f4e33f3dcb43bb32',
    messagingSenderId: '564462594743',
    projectId: 'wigo-trip-planner',
    storageBucket: 'wigo-trip-planner.appspot.com',
    iosBundleId: 'com.example.wigo',
  );

}